# Generated by Django 3.1.4 on 2020-12-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='room_name')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='create_at')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='create_at')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_meesages', to='chat.room')),
            ],
            options={
                'verbose_name_plural': 'Message',
            },
        ),
    ]
