# Generated by Django 3.1.4 on 2020-12-22 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='room',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_at'),
        ),
    ]
