# Generated by Django 3.1.4 on 2020-12-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201223_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Room'},
        ),
    ]
