# Generated by Django 3.1.4 on 2020-12-24 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joining_room',
            field=models.ManyToManyField(blank=True, related_name='joining_room', to='chat.Room'),
        ),
        migrations.AddField(
            model_name='userrelationship',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrelationship',
            name='relating_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relating_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
