# Generated by Django 3.1.4 on 2020-12-24 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201224_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelationship',
            name='relating_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='relating_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
