# Generated by Django 3.1.4 on 2020-12-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joining_room',
            field=models.ManyToManyField(blank=True, related_name='joining_room', to='chat.Room'),
        ),
    ]
